name: Hugo Deploy with Obsidian Sync

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Ensure destination directory exists
        run: mkdir -p content/posts

      - name: Sync Obsidian vault to Hugo content
        run: |
          rsync -av --delete obsidian/posts/ content/posts/

      - name: Run image processing
        run: |
          if [ -f images.py ]; then
            python3 images.py
          fi

      - name: Build Hugo site
        run: hugo

      # Upload the built site (public directory) as an artifact
      - name: Upload built site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: public/  # Ensure this is the correct directory for your Hugo build output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact-name: github-pages  # Reference the uploaded artifact name

